FORMAT: 1A
HOST: http://dev.banyan.space/

# KOT

## Login [/questions]

### Get Restaurant Login Info [POST /api/app/v1/login]
+ Request


    + Body
    
            {
                "password": "12345678",
                "email": "anil.saripiralla@gmail.com"
            }

+ Response 200 (application/json)

        {
        "restaurant": {
        "open_time": "10:00:00",
        "rest_id": 3,
        "name": "Banyan"
        },
        "user_id": 8,
        "mobile": "9515711117",
        "designation": 1,
        "permissions": [],
        "oauth_token": "Ci5819ab7esI8eFEThJryQAehJzgRwWa",
        "email": "anil.saripiralla@gmail.com",
        "refresh_token": "blknHpZO5819ab7eoPeGYDzs8vQ01b070f72hecoqdSNnHODdmwjdTbEgBJSDwocskefjukAwPpSIlmtcmXCdLyqnnCsBeiOBoXSUBGvgqckPUOTosquOInTNAmcbuPb",
        "name": "Anil"
        }

### GCM Register [POST /api/app/v1/kitchen_app/gcm_register?{gcm_reg_id,kitchen_id}]
+ Request
    
    + Headers
    
            oauth_token: db581302b1XH8YIOeoGBiQRrIKhpbfTy

+ Parameters
    + gcm_reg_id
    + kitchen_id

+ Response 200 (application/json)

        {
          "status": "OK",
          "status_code": 200
        }

### GCM UnRegister [POST /api/app/v1/kitchen_app/gcm_unregister?{gcm_reg_id,kitchen_id}]
+ Request
    
    + Headers
    
            oauth_token: db581302b1XH8YIOeoGBiQRrIKhpbfTy

+ Parameters
    + gcm_reg_id
    + kitchen_id

+ Response 200 (application/json)

        {
          "status": "OK",
          "status_code": 200
        }

### Get Pending GCM Messages [GET /api/app/v1/kitchen_app/get_pending_gcm_messages?]

+ Request
    
    + Headers
    
            oauth_token: db581302b1XH8YIOeoGBiQRrIKhpbfTy

+ Response 200 (application/json)
        
        [
        ]

### Get KOT Details [GET /api/app/v1/kitchen_app/kot_detail{?kot_id,tx_id,kitchen_id,kot_type}]

+ Request
    
    + Headers
    
            oauth_token: db581302b1XH8YIOeoGBiQRrIKhpbfTy
            
            
+ Parameters
    + kot_id
    + tx_id
    + kitchen_id
    + kot_type

+ Response 200 (application/json)

    + Body

            {
                "table_id": 10,
                "ts": 1478079280,
                "kot_time": 1478081182,
                "guest_name": "",
                "waiter_name": "Prudvin",
                "guest_mobile": "",
                "otype_id": 1,
                "otype_name": "Dine In",
                "bill_no": 1,
                "table_name": "A4",
                "order_items": [
                    {
                        "addon_string": null,
                        "primary": null,
                        "item_name": "Butter Scotch",
                        "custom_comment": "",
                        "serving": "standard",
                        "order_item_id": 1666,
                        "waiter_name": null,
                        "quantity": 2,
                        "kot_number": 2,
                        "waiter_id": 0
                    }
                ],
                "type": "New",
                "tx_id": 537
            }
            
            
### GET Kitchen Printers [GET /api/app/v1/kitchen_app/get_kitchen_printers]

+ Request
    
    + Headers
    
            oauth_token: db581302b1XH8YIOeoGBiQRrIKhpbfTy
            

            
+ Response 200 (application/json)


        [
            {
                "kitchen_id": 1,
                "kitchen_name": "Food",
                "ip_addr": "192.168.0.170",
                "printer_name": "EPSON"
                 
            },
            {
                 "kitchen_id": 2,
                 "kitchen_name": "Pantry",
                 "ip_addr": "192.168.0.180",
                 "printer_name": "EPSON1"
            },
            {
                 "kitchen_id": 3,
                 "kitchen_name": "Bar",
                 "ip_addr": "192.168.0.190",
                 "printer_name": "EPSON2"
            }
        ]